### ISSUE TITLE
大佬有兴趣做联通签到金币吗？

### ISSUE THREAD

**Issue by zhangt2333** [CodFrm/cas#4]
我上个月写了个爬虫，在树莓派上安稳跑了20+天，都能签到，后来应该是后端更新了，然后Login变成有有效期的，必须天天在手机上登录过一次，派上的脚本才能成功，水平比较次搁置了会儿，有兴趣可以联系我呀！

**Comment by CodFrm** [comment]
不清楚，之前做了联通签到，每一次自动登录，不过只能手机号登录，现在不知道还能不能用，这个项目暂时没维护了

[联通登录](https://github.com/CodFrm/cas/blob/master/app/common/api/ChinaUnicomPlatform.php#L79)
